name: Release GitHub Action

on:
  push:
    branches:
      - master

env:
  image: ghcr.io/navikt/yaml-validator
  legacy_image: ghcr.io/navikt/yaml-validator/yaml-validator

jobs:
  build:
    name: Build Docker container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
      - name: Generate version tags
        run: |
          version=$(cat version)
          echo "version=${version}" >> $GITHUB_ENV
      - name: Build Docker image
        run: |
          docker build --tag ${image}:${GITHUB_SHA} --tag ${image}:latest --tag ${image}:${version} .
      - name: Push Docker image to GHCR
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${GITHUB_TOKEN}" | docker login ghcr.io -u ${GITHUB_ACTOR} --password-stdin
          docker push ${image}:${GITHUB_SHA}
          docker push ${image}:${version}
          docker push ${image}:latest
          docker tag ${image}:${version} ${legacy_image}:${version}
          docker tag ${image}:latest ${legacy_image}:latest
          docker push ${legacy_image}:${version}
          docker push ${legacy_image}:latest

  release:
    name: Release versioned GitHub Action
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v6
    - name: Force create tag
      run: |
        git tag -f $(cat version)
        git push -f --tags
    - name: Recreate release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release delete $(cat version) --yes || true
        gh release create $(cat version) --target master
